FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    tcpdump \
    net-tools \
    iptables \
    && rm -rf /var/lib/apt/lists/*

RUN pip install scapy

WORKDIR /scripts

CMD ["python", "/scripts/modify_packet.py"]
